//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjectCsharpFSWF.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class FutbolSahesiEntities : DbContext
    {
        public FutbolSahesiEntities()
            : base("name=FutbolSahesiEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Meydancalar> Meydancalars { get; set; }
        public virtual DbSet<Mushteri> Mushteris { get; set; }
        public virtual DbSet<Otaqlar> Otaqlars { get; set; }
        public virtual DbSet<Booking> Bookings { get; set; }
    }
}
